### ISSUE TITLE
Error trying to run rbg-to-gif.py 

### ISSUE THREAD

**Issue by jep5350** [pimoroni/mlx90640-library#14]
I have the MLX90640 connected via Pimoroni Breakout Garden. Have not been successful in getting images back. This is an error I receive when trying to execute the rbg-to-gif.py script. Is there another way I can verify that my sensor is being recognized, in order to narrow down the issue? Hoping the error below can provide enough insight.

> rgb-to-gif.py - output a gif using ./rawrgb command.
> 
> Use ./rawrgb to grab frames from the MLX90640
> and render them into a gif.
> 
> You must have built the "rawrgb" executable first with "make"
> 
> Press Ctrl+C to save & exit!
> 
> 
> Got 0 bytes of data!
> Traceback (most recent call last):
>   File "rgb-to-gif.py", line 40, in <module>
>     image = Image.frombytes('RGB', (24, 32), frame)
>   File "/usr/lib/python3/dist-packages/PIL/Image.py", line 2100, in frombytes
>     im.frombytes(data, decoder_name, args)
>   File "/usr/lib/python3/dist-packages/PIL/Image.py", line 742, in frombytes
>     raise ValueError("not enough image data")
> ValueError: not enough image data
>

**Comment by robmarkcole** [comment]
I think this is the same issue as https://github.com/pimoroni/mlx90640-library/issues/13

**Comment by robmarkcole** [comment]
Found a bug
