### ISSUE TITLE
Gifs and images have checkerboard pattern with rgb-to-gif.py

### ISSUE THREAD

**Issue by robmarkcole** [pimoroni/mlx90640-library#16]
As title, example below

![image](https://user-images.githubusercontent.com/11855322/55951199-93e56680-5c4e-11e9-9214-4bcc7f6b6760.png)

Files [here](https://github.com/robmarkcole/mlx90640-library/tree/adds-rgd-to-file/python)

**Comment by Gadgetoid** [comment]
This may be due to your camera drifting out of sync. Here's an example I recorded while putting the python together: https://twitter.com/Gadgetoid/status/1115297867755814914

Have you modified the framerate in your version of rawrgb at all?

**Comment by robmarkcole** [comment]
No, is experimentation required?

**Comment by Gadgetoid** [comment]
Looks like there's something wrong with my conversion to gif- I think I'm treating the image as being the wrong aspect ratio perhaps.

I'm working on adding an `--fps` param, too, so it's easier to dial it down until it works.

**Comment by Gadgetoid** [comment]
This certainly helped fix the problem: https://github.com/pimoroni/mlx90640-library/commit/d2b282dd865c6f99df6fd6a3f97ccb41727b7658#diff-29eca65bc5a52a720033aadba07e3920

I've also added a command-line argument to both `rgb-to-gif.py` and `rawrgb` to let you specify a framerate, and have lowered the default framerate to one that's more likely to work for (hopefully) most users.

And here's a huge gif of me waving at what's supposed to be 4fps:

![mlx90640-2019-04-11-12-43-46](https://user-images.githubusercontent.com/1746967/55955089-55ed4000-5c58-11e9-9c7e-8d85518408f4.gif)

**Comment by robmarkcole** [comment]
Still a bit wild https://github.com/pimoroni/mlx90640-library/commit/d2b282dd865c6f99df6fd6a3f97ccb41727b7658#commitcomment-33139389

![mlx90640-2019-04-11-13-56-01](https://user-images.githubusercontent.com/11855322/55958902-98674a80-5c61-11e9-9bb6-6fe4ee645ba0.jpg)

**Comment by Gadgetoid** [comment]
Tried 1FPS? Also make sure you have nothing else on the i2c bus. Right now your data - looking at https://github.com/pimoroni/mlx90640-library/commit/d2b282dd865c6f99df6fd6a3f97ccb41727b7658#diff-29eca65bc5a52a720033aadba07e3920 - looks completely garbled.

Might be worth also running one of the C examples directly (sdlscale is one of the better ones) to see if you get the same result.

What version of the Pi is this on? How is the sensor connected to the Pi?

**Comment by robmarkcole** [comment]
As below. OK I restarted the Pi and Gifs look good. However now my `rgb-to-file.py` is now displaying a blank image. Something very funny going on here 

![image](https://user-images.githubusercontent.com/11855322/55962229-61486780-5c68-11e9-81a2-f5791c7654f9.png)

**Comment by Gadgetoid** [comment]
You'll need to solder a header on, or pick up a Breakout Garden. I2C will be an unreliable mess - as demonstrated by your camera feed - without a solid electrical connection.

Unsoldered IO pins are - literally - square pegs in round holes.

**Comment by robmarkcole** [comment]
I don't think thats the problem (although I agree this needs a solder!) as I capture the gifs just fine.

**Comment by Gadgetoid** [comment]
Just fine!?!?

![](https://user-images.githubusercontent.com/11855322/55958729-41617580-5c61-11e9-8787-c26f120c3bde.gif)

**Comment by Gadgetoid** [comment]
To be fair- I've just jammed my camera on in very much the same way and it works surprisingly well. Well kind of.

**Comment by robmarkcole** [comment]
After reboot

![mlx90640-2019-04-11-14-55-41](https://user-images.githubusercontent.com/11855322/55963410-ae2d3d80-5c6a-11e9-8497-f9221dbfd056.gif)

**Comment by Gadgetoid** [comment]
What the!? Wonders never cease.

Edit: You're getting the same dithering effect that's currently bugging me. I need to find a better way of converting these to a specific palette.

**Comment by robmarkcole** [comment]
OK so I saved each of the frames from the gif, the zeroth frame is blank

![mlx90640-0](https://user-images.githubusercontent.com/11855322/55963658-28f65880-5c6b-11e9-819e-11c69c96f6bf.jpg)

By frame 3 we are getting data

![mlx90640-3](https://user-images.githubusercontent.com/11855322/55963697-390e3800-5c6b-11e9-92a8-442346fc5804.jpg)

Frame 5 is starting to look reasonable

![mlx90640-5](https://user-images.githubusercontent.com/11855322/55963769-593df700-5c6b-11e9-858d-6f4c3cf1848d.jpg)

**Comment by Gadgetoid** [comment]
I reckon a `--drop-frames` argument would be a good addition, so you can specify how much data to throw away before the recording starts. Or perhaps it should be a timed delay. Would give much better loops, as the black frames currently break that.

Edit: Better!

![mlx90640-2019-04-11-15-16-13](https://user-images.githubusercontent.com/1746967/55964536-cbfba200-5c6c-11e9-89af-be1c580f5fc1.gif)

Note this is using a 32-colour adaptive palette for every single gif frame, so it's super inefficient. Building a fixed palette for this should get these images sizes much smaller.

**Comment by robmarkcole** [comment]
Nice! Thanks for your help on this one
