### ISSUE TITLE
Raspberry Pi4 with fb buffer not work?

### ISSUE THREAD

**Issue by imliubo** [pimoroni/mlx90640-library#33]
Hi @pimoroni,
I try to run fbuf example with pi4,but it seem not work.I followed the steps step by step.
![2019-10-19-220001_1920x1080_scrot](https://user-images.githubusercontent.com/26544331/67146556-c5568300-f2be-11e9-8a00-2e9efbccb692.png)

**Comment by roblevine** [comment]
I get the same on my PI4 too

**Comment by imliubo** [comment]
@roblevine sdlscale example is better than fb example.But the fb example still not work...

**Comment by Gadgetoid** [comment]
Sincee `fbuf` attempts to draw directly to the framebuffer, it's probably fundamentally incompatible with how the X desktop works on the Pi 4, and isn't really intended to be run inside a desktop session anyway. You should use `sdlscale`.
