### ISSUE TITLE
Save as jpg

### ISSUE THREAD

**Issue by Jooslee0313** [pimoroni/mlx90640-library#45]
I changed some code for save as jpg.
But there is error happen What I can't solve.
how can I save as jpg without error?
=======================
Original code
filename = 'mlx90640-{}.gif'.format(
   datetime.now().strftime("%Y-%m-%d-%H-%M-%S"))
print("Saving {} with {} frames.".format(filename, len(frames)))
frames[0].save(
   filename,
   save_all=True,
   append_images=frames[1:],
   duration=1000 // fps,
   loop=0,
   include_color_table=True,
   optimize=True,
   palette=master.palette.getdata())

----->
for i, fr in enumerate(frames):
    filename = "mlx90640-{}-{}.jpg".format(datetime.now().strftime("%Y-%m-%d-%H-%M-%S"), i)
    print("Saving {}".format(filename))
    fr.save(filename)

=======================
Result : 

rgb-to-gif.py - output a gif using ./rawrgb command.
Use ./rawrgb to grab frames from the MLX90640
and render them into a gif.
You must have built the "rawrgb" executable first with "make"
Press Ctrl+C to save & exit!

Got 2304 bytes of data!
Got 2304 bytes of data!
Got 2304 bytes of data!
Frames: 1
Got 2304 bytes of data!
Frames: 2
Got 2304 bytes of data!
Frames: 3
Got 2304 bytes of data!
Frames: 4
Got 2304 bytes of data!
Frames: 5
Saving mlx90640-2020-02-27-22-34-10-0.jpg
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/PIL/JpegImagePlugin.py", line 620, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'P'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/mlx90640-library/python/Image.py", line 82, in <module>
    fr.save(filename)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1994, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3/dist-packages/PIL/JpegImagePlugin.py", line 622, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode P as JPEG

**Comment by Gadgetoid** [comment]
LMGTFY https://stackoverflow.com/questions/21669657/getting-cannot-write-mode-p-as-jpeg-while-operating-on-jpg-image
