### ISSUE TITLE
protect dust and humid: add Transparent Glass with lens. 

### ISSUE THREAD

**Issue by suchit1989** [pimoroni/mlx90640-library#49]
Hi Support,
Face recognize product with thermal support we are using mlx90640. We want put transparent glass in front of camera lens to protect dust and humid. Is there any temperature impact with Glass?

www.invixium.com

**Comment by Gadgetoid** [comment]
You should talk to Melexis, read the datasheet or conduct your own tests. Testing suitability for any particular purpose is outsite the remit of this software library.
