### ISSUE TITLE
mlx90640 and pi 4

### ISSUE THREAD

**Issue by srscotty** [pimoroni/mlx90640-library#52]
Something strange I have noticed is while the examples work fine on Pi 3, I cannot get them to run in the foreground on pi 4. I have tried several times, unsuccessfully. When I ctrl-alt-F1 the gui, I see it running in the background. Any ideas?

**Comment by Gadgetoid** [comment]
I think `dtoverlay=vc4-fkms-v3d` breaks the framebuffer examples. You'll need to comment that out in `/boot/config.txt`

**Comment by srscotty** [comment]
That did the trick. Just like magic
