### ISSUE TITLE
unneeded stdio output for python driver

### ISSUE THREAD

**Issue by timsoftgit** [pimoroni/mlx90640-library#9]
mlx90640-python.cpp lines 139,143,148 and 158 could be commented out. as a camera module/driver, you don't expect stdio output, it interferes with output from any program using it, and if they are just commented out, it still shows anyone looking at the code what is happening.

**Comment by Gadgetoid** [comment]
Agreed. These were present for debug purposes as I'm still not satisfied with the Python driver. I've relegated them to an `ifdef`.
